name: LinuxBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: archlinux

    steps:
      # - name: Install Crystal
      #   uses: oprypin/install-crystal@v1
      #   with: 
      #     crystal: latest
      - name: update docker
        run: pacman -Syu --noconfirm
      
      - name: install crystal 
        run: pacman -S gcc make cmake crystal shards --noconfirm
      
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: shards install
        env:
          SHARDS_OPTS: --ignore-crystal-version

      - name: Build Project
        run: crystal build helloworld.cr

      - name: Bulid Project 2
        run: crystal build helloworld2.cr