name: LinuxBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with: 
          crystal: latest
      
      
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: shards install
        env:
          SHARDS_OPTS: --ignore-crystal-version

      - name: Build Project
        run: crystal build helloworld.cr