name: LinuxBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: archlinux

    steps:
      - name: update docker
        run: pacman -Syu --noconfirm
      
      - name: install dependancies 
        run: pacman -S base-devel gcc make cmake openssl crystal shards --noconfirm
      
      - uses: actions/checkout@v2

      - name: Install shard dependencies
        run: shards install
        env:
          SHARDS_OPTS: --ignore-crystal-version

      - name: Build Project
        run: crystal build helloworld.cr

      - name: Bulid Project 2
        run: crystal build helloworld2.cr

      - name: upload to git 
        uses: actions/upload-release-asset@v1.0.1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./
        asset_name: helloworld-${{ github.event.release.tag_name }}-arch-linux-x86_64
        asset_content_type: binary/octet-stream